<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ PowerAuth Enrollment Server
  ~ Copyright (C) 2021 Wultra s.r.o.
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU Affero General Public License as published
  ~ by the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU Affero General Public License for more details.
  ~
  ~ You should have received a copy of the GNU Affero General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <name>enrollment-server-parent</name>
    <description>Enrollment Server Parent</description>

    <groupId>com.wultra.security</groupId>
    <artifactId>enrollment-server-parent</artifactId>
    <version>2.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.5.8</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <inceptionYear>2021</inceptionYear>
    <url>https://powerauth.com/</url>

    <organization>
        <name>Wultra s.r.o.</name>
        <url>https://wultra.com/</url>
    </organization>

    <licenses>
        <license>
            <name>GNU Affero General Public License v3.0</name>
            <url>https://www.gnu.org/licenses/agpl-3.0.en.html</url>
        </license>
    </licenses>

    <developers>
        <developer>
            <name>Petr Dvorak</name>
            <email>petr@wultra.com</email>
            <roles>
                <role>developer</role>
            </roles>
        </developer>
    </developers>

    <scm>
        <connection>scm:git:https://github.com/wultra/enrollment-server.git</connection>
        <developerConnection>scm:git:https://github.com/wultra/enrollment-server.git</developerConnection>
        <url>https://github.com/wultra/enrollment-server</url>
    </scm>

    <issueManagement>
        <system>Github</system>
        <url>https://github.com/wultra/enrollment-server/issues</url>
    </issueManagement>

    <modules>
        <module>mtoken-model</module>
        <module>enrollment-server-api-model</module>
        <module>enrollment-server</module>
        <module>enrollment-server-onboarding</module>
        <module>enrollment-server-onboarding-api</module>
        <module>enrollment-server-onboarding-api-model</module>
        <module>enrollment-server-onboarding-adapter-mock</module>
        <module>enrollment-server-onboarding-common</module>
        <module>enrollment-server-onboarding-domain-model</module>
        <module>enrollment-server-onboarding-provider-innovatrics</module>
        <module>enrollment-server-onboarding-provider-iproov</module>
        <module>enrollment-server-onboarding-provider-microblink</module>
        <module>enrollment-server-onboarding-provider-zenid</module>
    </modules>

    <properties>
        <openapi-generator-maven-plugin.version>7.20.0</openapi-generator-maven-plugin.version>

        <okhttp3.version>5.3.2</okhttp3.version>
        <shedlock.version>6.10.0</shedlock.version>
        <spring-statemachine.version>4.0.1</spring-statemachine.version>
        <swagger-annotations-jakarta.version>2.2.43</swagger-annotations-jakarta.version>
        <springdoc-openapi-starter-webmvc-ui.version>2.8.16</springdoc-openapi-starter-webmvc-ui.version>
        <moneta.version>1.4.5</moneta.version>
        <central.publishing.plugin.version>0.10.0</central.publishing.plugin.version>

        <wultra-core.version>2.0.0</wultra-core.version>
        <powerauth-crypto.version>2.0.1</powerauth-crypto.version>
        <powerauth-restful-integration.version>2.0.0</powerauth-restful-integration.version>
        <powerauth-push.version>2.0.1</powerauth-push.version>

        <logstash.version>8.1</logstash.version>
        <cyclonedx-maven-plugin.version>2.9.1</cyclonedx-maven-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>enrollment-server-api-model</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>enrollment-server-onboarding-common</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>enrollment-server-onboarding-api</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>enrollment-server-onboarding-provider-innovatrics</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>enrollment-server-onboarding-provider-iproov</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>enrollment-server-onboarding-provider-microblink</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>enrollment-server-onboarding-provider-zenid</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>mtoken-model</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.core</groupId>
                <artifactId>annotations</artifactId>
                <version>${wultra-core.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.core</groupId>
                <artifactId>rest-client-base</artifactId>
                <version>${wultra-core.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.core</groupId>
                <artifactId>rest-model-base</artifactId>
                <version>${wultra-core.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.core</groupId>
                <artifactId>audit-base</artifactId>
                <version>${wultra-core.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.core</groupId>
                <artifactId>http-common</artifactId>
                <version>${wultra-core.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>powerauth-java-crypto</artifactId>
                <version>${powerauth-crypto.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>powerauth-restful-security-spring-annotation</artifactId>
                <version>${powerauth-restful-integration.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>powerauth-restful-security-spring</artifactId>
                <version>${powerauth-restful-integration.version}</version>
            </dependency>

            <dependency>
                <groupId>com.wultra.security</groupId>
                <artifactId>powerauth-push-client</artifactId>
                <version>${powerauth-push.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-el</artifactId>
                <version>${tomcat.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>org.javamoney.moneta</groupId>
                <artifactId>moneta-core</artifactId>
                <version>${moneta.version}</version>
            </dependency>

            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-annotations-jakarta</artifactId>
                <version>${swagger-annotations-jakarta.version}</version>
            </dependency>

            <!-- Logging -->
            <dependency>
                <groupId>net.logstash.logback</groupId>
                <artifactId>logstash-logback-encoder</artifactId>
                <version>${logstash.version}</version>
            </dependency>

            <!-- Documentation -->
            <dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
                <version>${springdoc-openapi-starter-webmvc-ui.version}</version>
            </dependency>

            <!-- Job Scheduling -->
            <dependency>
                <groupId>net.javacrumbs.shedlock</groupId>
                <artifactId>shedlock-bom</artifactId>
                <version>${shedlock.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Testing -->
            <dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>mockwebserver</artifactId>
                <version>${okhttp3.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.sonatype.central</groupId>
                    <artifactId>central-publishing-maven-plugin</artifactId>
                    <version>${central.publishing.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>io.github.git-commit-id</groupId>
                    <artifactId>git-commit-id-maven-plugin</artifactId>
                    <version>${git-commit-id-maven-plugin.version}</version>
                    <executions>
                        <execution>
                            <id>get-the-git-infos</id>
                            <goals>
                                <goal>revision</goal>
                            </goals>
                            <phase>initialize</phase>
                        </execution>
                    </executions>
                    <configuration>
                        <generateGitPropertiesFile>true</generateGitPropertiesFile>
                        <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
                        <commitIdGenerationMode>full</commitIdGenerationMode>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <excludedGroups>external-service</excludedGroups>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven-source-plugin.version}</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>${maven-javadoc-plugin.version}</version>
                <configuration>
                    <failOnError>false</failOnError>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <executions>
                    <execution>
                        <id>enforce-banned-dependencies</id>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <bannedDependencies>
                                    <excludes>
                                        <exclude>org.apache.tomcat.embed:*:*:*:compile</exclude>
                                        <exclude>org.bouncycastle:bcpkix-jdk15on:*:*:compile</exclude>
                                        <exclude>org.bouncycastle:bcprov-jdk15on:*:*:compile</exclude>
                                        <exclude>com.google.guava:guava*:*:*:compile</exclude>
                                    </excludes>
                                </bannedDependencies>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.cyclonedx</groupId>
                <artifactId>cyclonedx-maven-plugin</artifactId>
                <version>${cyclonedx-maven-plugin.version}</version>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>release-sign-artifacts</id>
            <activation>
                <property>
                    <name>performRelease</name>
                    <value>true</value>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.kohsuke</groupId>
                        <artifactId>pgp-maven-plugin</artifactId>
                        <version>1.1</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>sign</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
        <profile>
            <id>internal-repository</id>
            <activation>
                <property>
                    <name>useInternalRepo</name>
                    <value>true</value>
                </property>
            </activation>
            <properties>
            </properties>
            <distributionManagement>
                <repository>
                    <id>jfrog-central</id>
                    <name>Wultra Artifactory-releases</name>
                    <url>https://wultra.jfrog.io/artifactory/internal-maven-repository</url>
                </repository>
                <snapshotRepository>
                    <id>jfrog-central</id>
                    <name>Wultra Artifactory-snapshots</name>
                    <url>https://wultra.jfrog.io/artifactory/internal-maven-repository</url>
                </snapshotRepository>
            </distributionManagement>
            <repositories>
                <repository>
                    <id>jfrog-central</id>
                    <name>Wultra Artifactory-releases</name>
                    <url>https://wultra.jfrog.io/artifactory/internal-maven-repository</url>
                </repository>
                <repository>
                    <id>central-portal-snapshots</id>
                    <url>https://central.sonatype.com/repository/maven-snapshots/</url>
                    <releases>
                        <enabled>false</enabled>
                    </releases>
                    <snapshots>
                        <enabled>true</enabled>
                    </snapshots>
                </repository>
            </repositories>
        </profile>
        <profile>
            <id>public-repository</id>
            <activation>
                <property>
                    <name>!useInternalRepo</name>
                </property>
            </activation>
            <distributionManagement>
                <snapshotRepository>
                    <id>central-portal-snapshots-distribution</id>
                    <url>https://central.sonatype.com/repository/maven-snapshots/</url>
                </snapshotRepository>
                <repository>
                    <id>central-portal-staging-distribution</id>
                    <url>https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/</url>
                </repository>
            </distributionManagement>
            <properties>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.sonatype.central</groupId>
                        <artifactId>central-publishing-maven-plugin</artifactId>
                        <extensions>true</extensions>
                        <configuration>
                            <publishingServerId>${env.server_id}</publishingServerId>
                            <autoPublish>true</autoPublish>
                            <waitUntil>published</waitUntil>
                            <waitMaxTime>${env.wait_max_time}</waitMaxTime>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <repositories>
        <repository>
            <id>central-portal-snapshots</id>
            <url>https://central.sonatype.com/repository/maven-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

</project>
