#
# PowerAuth Enrollment Server
# Copyright (C) 2020 Wultra s.r.o.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Allow externalization of properties using application-ext.properties
spring.profiles.active=ext

spring.application.name=onboarding-server

banner.application.name=${spring.application.name}
banner.application.version=@project.version@

# Database Configuration - PostgreSQL
spring.datasource.url=${ENROLLMENT_SERVER_ONBOARDING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/powerauth}
spring.datasource.username=${ENROLLMENT_SERVER_ONBOARDING_DATASOURCE_USERNAME:powerauth}
spring.datasource.password=${ENROLLMENT_SERVER_ONBOARDING_DATASOURCE_PASSWORD:}
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.pool-name=HikariPool-Enrollment-Server-Onboarding
spring.jpa.properties.hibernate.connection.characterEncoding=${ENROLLMENT_SERVER_ONBOARDING_JPA_CHARACTER_ENCODING:utf8}
spring.jpa.properties.hibernate.connection.useUnicode=${ENROLLMENT_SERVER_ONBOARDING_JPA_USE_UNICODE:true}
spring.jpa.properties.jakarta.persistence.validation.group.pre-persist=jakarta.validation.groups.Default,com.wultra.app.onboardingserver.common.validation.NotNullOnCreate

# Database Configuration - Oracle
#spring.datasource.url=jdbc:oracle:thin:@//127.0.0.1:1521/powerauth
#spring.datasource.username=powerauth
#spring.datasource.password=

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none

# Bouncy Castle initialization
bouncycastle.provider.initialization.enabled=true

# Database Lock Timeout Configuration
spring.jpa.properties.jakarta.persistence.lock.timeout=${ENROLLMENT_SERVER_ONBOARDING_JPA_LOCK_TIMEOUT:10000}

# Disable open session in view to avoid startup warning of Spring boot
spring.jpa.open-in-view=false

# Set JMX default domain in case JMX is enabled, otherwise the application startup fails due to clash in JMX bean names
spring.jmx.default-domain=enrollment-server-onboarding

# Configure Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ssZ

# Disable swagger-ui default petstore url
springdoc.swagger-ui.disable-swagger-default-url=true

# Overriding default value of 1 to allow running multiple scheduled tasks in parallel
spring.task.scheduling.pool.size=5

# PowerAuth service configuration
powerauth.service.url=${ENROLLMENT_SERVER_ONBOARDING_POWERAUTH_SERVICE_URL:http://localhost:8080/powerauth-java-server/rest}
powerauth.service.restClientConfig.responseTimeout=${ENROLLMENT_SERVER_ONBOARDING_POWERAUTH_SERVICE_RESPONSE_TIMEOUT:60s}
powerauth.service.restClientConfig.maxIdleTime=${ENROLLMENT_SERVER_ONBOARDING_POWERAUTH_SERVICE_MAX_IDLE_TIME:200s}
powerauth.service.security.clientToken=${ENROLLMENT_SERVER_ONBOARDING_POWERAUTH_SERVICE_SECURITY_CLIENT_TOKEN:}
powerauth.service.security.clientSecret=${ENROLLMENT_SERVER_ONBOARDING_POWERAUTH_SERVICE_SECURITY_CLIENT_SECRET:}

enrollment-server-onboarding.security.auth-type=BASIC_AUTH

# Onboarding Process Configuration
enrollment-server-onboarding.onboarding-process.otp.length=8
enrollment-server-onboarding.onboarding-process.otp.expiration=5m
enrollment-server-onboarding.onboarding-process.otp.max-failed-attempts=5
enrollment-server-onboarding.onboarding-process.otp.resend-period=30s
enrollment-server-onboarding.onboarding-process.expiration=3h
enrollment-server-onboarding.onboarding-process.activation.expiration=5m
enrollment-server-onboarding.onboarding-process.verification.expiration=1h
enrollment-server-onboarding.onboarding-process.max-processes-per-day=5
enrollment-server-onboarding.onboarding-process.max-error-score=15
enrollment-server-onboarding.onboarding-process.default-type=${ENROLLMENT_SERVER_ONBOARDING_PROCESS_DEFAULT_TYPE:}

# Onboarding Adapter Configuration
# defining the URL enables the RestOnboardingProvider
#enrollment-server-onboarding.onboarding-adapter.url=http://localhost:8090
enrollment-server-onboarding.onboarding-adapter.connection-timeout=2s
enrollment-server-onboarding.onboarding-adapter.handshake-timeout=5s
enrollment-server-onboarding.onboarding-adapter.response-timeout=60s
enrollment-server-onboarding.onboarding-adapter.max-idle-time=200s
enrollment-server-onboarding.onboarding-adapter.max-life-time=1h
#enrollment-server-onboarding.onboarding-adapter.accept-invalid-ssl-certificate=false
#enrollment-server-onboarding.onboarding-adapter.http-basic-auth-enabled=false
#enrollment-server-onboarding.onboarding-adapter.http-basic-auth-username=
#enrollment-server-onboarding.onboarding-adapter.http-basic-auth-password=
#enrollment-server-onboarding.onboarding-adapter.correlation-header.name=X-Correlation-Id
#enrollment-server-onboarding.onboarding-adapter.request-id-header.name=X-Request-Id
#enrollment-server-onboarding.onboarding-adapter.headers.X-Custom-Header=foo

# Client Evaluation Configuration
enrollment-server-onboarding.client-evaluation.max-failed-attempts=5
enrollment-server-onboarding.client-evaluation.include-extracted-data=false

# Identity Verification Configuration
enrollment-server-onboarding.identity-verification.enabled=${ENROLLMENT_SERVER_ONBOARDING_IDENTITY_VERIFICATION_ENABLED:false}
enrollment-server-onboarding.identity-verification.data-retention=1h
enrollment-server-onboarding.identity-verification.max-failed-attempts=5
enrollment-server-onboarding.identity-verification.max-failed-attempts-document-upload=5

# Provider Configuration
#enrollment-server-onboarding.document-verification.provider=zenid
#enrollment-server-onboarding.document-verification.provider=innovatrics
enrollment-server-onboarding.document-verification.provider=${ENROLLMENT_SERVER_ONBOARDING_DOCUMENT_VERIFICATION_PROVIDER:mock}
enrollment-server-onboarding.document-verification.cleanupEnabled=false
enrollment-server-onboarding.document-verification.checkInProgressDocumentSubmits.cron=-
enrollment-server-onboarding.document-verification.checkDocumentsVerifications.cron=-
enrollment-server-onboarding.document-verification.checkDocumentSubmitVerifications.cron=-

enrollment-server-onboarding.presence-check.enabled=true
#enrollment-server-onboarding.presence-check.provider=iproov
#enrollment-server-onboarding.presence-check.provider=innovatrics
enrollment-server-onboarding.presence-check.provider=${ENROLLMENT_SERVER_ONBOARDING_PRESENCE_CHECK_PROVIDER:mock}
enrollment-server-onboarding.presence-check.cleanupEnabled=false
# Enables/disabled verification of the presence check selfie photo with the documents
enrollment-server-onboarding.presence-check.verifySelfieWithDocumentsEnabled=false
enrollment-server-onboarding.presence-check.max-failed-attempts=5
enrollment-server-onboarding.presence-check.selfie.minimal-width=400

# Microblink configuration
enrollment-server-onboarding.document-verification.microblink.restClientConfig.baseUrl=${ENROLLMENT_SERVER_ONBOARDING_MICROBLINK_SERVICE_BASE_URL}
enrollment-server-onboarding.document-verification.microblink.restClientConfig.httpBasicAuthEnabled=true
enrollment-server-onboarding.document-verification.microblink.restClientConfig.httpBasicAuthUsername=${ENROLLMENT_SERVER_ONBOARDING_MICROBLINK_HTTP_BASIC_AUTH_USERNAME}
enrollment-server-onboarding.document-verification.microblink.restClientConfig.httpBasicAuthPassword=${ENROLLMENT_SERVER_ONBOARDING_MICROBLINK_HTTP_BASIC_AUTH_PASSWORD}
enrollment-server-onboarding.document-verification.microblink.restClientConfig.connectionTimeout=5s
enrollment-server-onboarding.document-verification.microblink.restClientConfig.responseTimeout=60s
enrollment-server-onboarding.document-verification.microblink.restClientConfig.maxIdleTime=200s
enrollment-server-onboarding.document-verification.microblink.restClientConfig.maxLifeTime=1h
enrollment-server-onboarding.document-verification.microblink.extractedDataCheckEnabled=true
enrollment-server-onboarding.document-verification.microblink.request-options.returnFaceImage=true
enrollment-server-onboarding.document-verification.microblink.request-options.returnImageFormat=Jpg
enrollment-server-onboarding.document-verification.microblink.request-options.returnFullDocumentImage=true

# ZenID configuration
enrollment-server-onboarding.document-verification.zenid.apiKey=${ENROLLMENT_SERVER_ONBOARDING_ZENID_API_KEY}
enrollment-server-onboarding.document-verification.zenid.additionalDocSubmitValidationsEnabled=${ENROLLMENT_SERVER_ONBOARDING_ZENID_ADDITIONAL_DOC_SUBMIT_VALIDATIONS_ENABLED:true}
enrollment-server-onboarding.document-verification.zenid.asyncProcessingEnabled=${ENROLLMENT_SERVER_ONBOARDING_ZENID_ASYNC_PROCESSING_ENABLED:false}
enrollment-server-onboarding.document-verification.zenid.documentCountry=Cz
#enrollment-server-onboarding.document-verification.zenid.profile=
enrollment-server-onboarding.document-verification.zenid.serviceBaseUrl=${ENROLLMENT_SERVER_ONBOARDING_ZENID_SERVICE_BASE_URL}
enrollment-server-onboarding.document-verification.zenid.serviceUserAgent=Wultra/OnboardingServer

# ZenID REST client configuration
enrollment-server-onboarding.document-verification.zenid.restClientConfig.acceptInvalidSslCertificate=false
enrollment-server-onboarding.document-verification.zenid.restClientConfig.maxInMemorySize=10485760
enrollment-server-onboarding.document-verification.zenid.restClientConfig.proxyEnabled=false
enrollment-server-onboarding.document-verification.zenid.restClientConfig.proxyHost=
enrollment-server-onboarding.document-verification.zenid.restClientConfig.proxyPort=0
enrollment-server-onboarding.document-verification.zenid.restClientConfig.proxyUsername=
enrollment-server-onboarding.document-verification.zenid.restClientConfig.proxyPassword=
enrollment-server-onboarding.document-verification.zenid.restClientConfig.connectionTimeout=10000
enrollment-server-onboarding.document-verification.zenid.restClientConfig.responseTimeout=60000
enrollment-server-onboarding.document-verification.zenid.restClientConfig.jacksonConfiguration.serialization.FAIL_ON_EMPTY_BEANS=false
enrollment-server-onboarding.document-verification.zenid.restClientConfig.jacksonConfiguration.serialization.WRITE_DATES_AS_TIMESTAMPS=false
enrollment-server-onboarding.document-verification.zenid.restClientConfig.jacksonConfiguration.serialization.WRITE_DATES_WITH_ZONE_ID=true
enrollment-server-onboarding.document-verification.zenid.restClientConfig.jacksonConfiguration.deserialization.ADJUST_DATES_TO_CONTEXT_TIME_ZONE=false
enrollment-server-onboarding.document-verification.zenid.restClientConfig.jacksonConfiguration.deserialization.FAIL_ON_UNKNOWN_PROPERTIES=false

# iProov configuration
enrollment-server-onboarding.presence-check.iproov.apiKey=${ENROLLMENT_SERVER_ONBOARDING_IPROOV_API_KEY}
enrollment-server-onboarding.presence-check.iproov.apiSecret=${ENROLLMENT_SERVER_ONBOARDING_IPROOV_API_SECRET}
enrollment-server-onboarding.presence-check.iproov.assuranceType=${ENROLLMENT_SERVER_ONBOARDING_IPROOV_ASSURANCE_TYPE:genuine_presence}
enrollment-server-onboarding.presence-check.iproov.ensureUserIdValueEnabled=${ENROLLMENT_SERVER_ONBOARDING_IPROOV_ENSURE_USER_ID_VALUE_ENABLED:false}
enrollment-server-onboarding.presence-check.iproov.riskProfile=${ENROLLMENT_SERVER_ONBOARDING_IPROOV_RISK_PROFILE:}
enrollment-server-onboarding.presence-check.iproov.serviceBaseUrl=${ENROLLMENT_SERVER_ONBOARDING_IPROOV_SERVICE_BASE_URL}
enrollment-server-onboarding.presence-check.iproov.serviceUserAgent=Wultra/OnboardingServer
enrollment-server-onboarding.presence-check.iproov.oAuthClientUsername=${ENROLLMENT_SERVER_ONBOARDING_IPROOV_OAUTH_CLIENT_USERNAME:}
enrollment-server-onboarding.presence-check.iproov.oAuthClientPassword=${ENROLLMENT_SERVER_ONBOARDING_IPROOV_OAUTH_CLIENT_PASSWORD:}

# iProov REST client configuration
enrollment-server-onboarding.presence-check.iproov.restClientConfig.acceptInvalidSslCertificate=false
enrollment-server-onboarding.presence-check.iproov.restClientConfig.maxInMemorySize=10485760
enrollment-server-onboarding.presence-check.iproov.restClientConfig.proxyEnabled=false
enrollment-server-onboarding.presence-check.iproov.restClientConfig.proxyHost=
enrollment-server-onboarding.presence-check.iproov.restClientConfig.proxyPort=0
enrollment-server-onboarding.presence-check.iproov.restClientConfig.proxyUsername=
enrollment-server-onboarding.presence-check.iproov.restClientConfig.proxyPassword=
enrollment-server-onboarding.presence-check.iproov.restClientConfig.connectionTimeout=10000
enrollment-server-onboarding.presence-check.iproov.restClientConfig.responseTimeout=60000
enrollment-server-onboarding.presence-check.iproov.restClientConfig.maxIdleTime=200s

# Innovatrics common configuration
enrollment-server-onboarding.provider.innovatrics.serviceBaseUrl=${ENROLLMENT_SERVER_ONBOARDING_INNOVATRICS_SERVICE_BASE_URL}
enrollment-server-onboarding.provider.innovatrics.serviceToken=${ENROLLMENT_SERVER_ONBOARDING_INNOVATRICS_SERVICE_TOKEN}
enrollment-server-onboarding.provider.innovatrics.serviceUserAgent=Wultra/OnboardingServer

# Innovatrics presence-check configuration
enrollment-server-onboarding.provider.innovatrics.presenceCheckConfiguration.score=0.875

# Innovatrics document-verification configuration
enrollment-server-onboarding.provider.innovatrics.documentVerificationConfiguration.documentCountries=CZE

# Innovatrics REST client configuration
enrollment-server-onboarding.provider.innovatrics.restClientConfig.acceptInvalidSslCertificate=false
enrollment-server-onboarding.provider.innovatrics.restClientConfig.maxInMemorySize=10485760
enrollment-server-onboarding.provider.innovatrics.restClientConfig.proxyEnabled=false
enrollment-server-onboarding.provider.innovatrics.restClientConfig.proxyHost=
enrollment-server-onboarding.provider.innovatrics.restClientConfig.proxyPort=0
enrollment-server-onboarding.provider.innovatrics.restClientConfig.proxyUsername=
enrollment-server-onboarding.provider.innovatrics.restClientConfig.proxyPassword=
enrollment-server-onboarding.provider.innovatrics.restClientConfig.connectionTimeout=10000
enrollment-server-onboarding.provider.innovatrics.restClientConfig.responseTimeout=60000
enrollment-server-onboarding.provider.innovatrics.restClientConfig.maxIdleTime=200s

spring.security.oauth2.client.provider.app.token-uri=${ENROLLMENT_SERVER_ONBOARDING_SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_APP:http://localhost:6060/oauth/token}


enrollment-server-onboarding.state-machine.changeMachineState.cron=0/3 * * * * *

# Maximum request and file size
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.max-file-size=50MB

# Incoming request debug logging
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Configure Correlation HTTP Header
powerauth.service.correlation-header.enabled=${ENROLLMENT_SERVER_ONBOARDING_CORRELATION_HEADER_ENABLED:false}
powerauth.service.correlation-header.name=${ENROLLMENT_SERVER_ONBOARDING_CORRELATION_HEADER_NAME:X-Correlation-ID}
powerauth.service.correlation-header.value.validation-regexp=${ENROLLMENT_SERVER_ONBOARDING_CORRELATION_HEADER_VALUE_VALIDATION_REGEXP:[a-zA-Z0-9\\-]{8,1024}}
# For logging correlation HTTP headers enable the pattern and update correlation header name in the pattern
#logging.pattern.console=%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) [%X{X-Correlation-ID}] %clr(%5p) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

# Monitoring
management.tracing.sampling.probability=1.0
#management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=health,info
management.info.git.mode=simple
#management.endpoint.prometheus.enabled=true
#management.prometheus.metrics.export.enabled=true

spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.metrics.jersey.JerseyServerMetricsAutoConfiguration
