enrollment-server-onboarding.identity-verification.enabled=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-module.xml

enrollment-server-onboarding.onboarding-process.default-type=onboarding

spring.security.user.name=admin
spring.security.user.password={bcrypt}$2a$10$Im45aSJeMpove4pF8/ypB.ufkITjfjpFvby9AMkvy.hrOVixkfkxq

logging.level.com.wultra=DEBUG
logging.level.com.wultra.core.audit=INFO
logging.level.com.wultra.app.onboardingserver.task=INFO
