enrollment-server-onboarding.identity-verification.enabled=true

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-module.xml

enrollment-server-onboarding.onboarding-process.default-type=onboarding

spring.security.user.name=admin
# Override locally if you need a different development password.
spring.security.user.password=${ENROLLMENT_SERVER_ONBOARDING_DEV_SECURITY_USER_PASSWORD:{noop}changeit}

logging.level.com.wultra=DEBUG
logging.level.com.wultra.core.audit=INFO
logging.level.com.wultra.app.onboardingserver.task=INFO
