#
# PowerAuth Enrollment Server
# Copyright (C) 2020 Wultra s.r.o.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# Allow externalization of properties using application-ext.properties
spring.profiles.active=ext

spring.application.name=enrollment-server

banner.application.name=${spring.application.name}
banner.application.version=@project.version@

# Database Configuration - PostgreSQL
spring.datasource.url=${ENROLLMENT_SERVER_DATASOURCE_URL:jdbc:postgresql://localhost:5432/powerauth}
spring.datasource.username=${ENROLLMENT_SERVER_DATASOURCE_USERNAME:powerauth}
spring.datasource.password=${ENROLLMENT_SERVER_DATASOURCE_PASSWORD:}
spring.datasource.hikari.auto-commit=false
spring.datasource.hikari.pool-name=HikariPool-Enrollment-Server
spring.jpa.properties.hibernate.connection.CharSet=${ENROLLMENT_SERVER_JPA_CHARSET:utf8}
spring.jpa.properties.hibernate.connection.characterEncoding=${ENROLLMENT_SERVER_JPA_CHARACTER_ENCODING:utf8}
spring.jpa.properties.hibernate.connection.useUnicode=${ENROLLMENT_SERVER_JPA_USE_UNICODE:true}

# Database Configuration - Oracle
#spring.datasource.url=jdbc:oracle:thin:@//127.0.0.1:1521/powerauth
#spring.datasource.username=powerauth
#spring.datasource.password=

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none

# Bouncy Castle initialization
bouncycastle.provider.initialization.enabled=true

# Database Lock Timeout Configuration
spring.jpa.properties.jakarta.persistence.lock.timeout=${ENROLLMENT_SERVER_JPA_LOCK_TIMEOUT:10000}

# Disable open session in view to avoid startup warning of Spring boot
spring.jpa.open-in-view=false

# Set JMX default domain in case JMX is enabled, otherwise the application startup fails due to clash in JMX bean names
spring.jmx.default-domain=enrollment-server

# Configure Jackson
spring.jackson.default-property-inclusion=non_null
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ssZ

# Disable swagger-ui default petstore url
springdoc.swagger-ui.disable-swagger-default-url=true

# Overriding default value of 1 to allow running multiple scheduled tasks in parallel
spring.task.scheduling.pool.size=5

# PowerAuth service configuration
powerauth.service.url=${ENROLLMENT_SERVER_POWERAUTH_SERVICE_URL:http://localhost:8080/powerauth-java-server/rest}
powerauth.service.restClientConfig.responseTimeout=${ENROLLMENT_SERVER_POWERAUTH_SERVICE_RESPONSE_TIMEOUT:60s}
powerauth.service.restClientConfig.maxIdleTime=${ENROLLMENT_SERVER_POWERAUTH_SERVICE_MAX_IDLE_TIME:200s}
powerauth.service.security.clientToken=${ENROLLMENT_SERVER_POWERAUTH_SERVICE_SECURITY_CLIENT_TOKEN:}
powerauth.service.security.clientSecret=${ENROLLMENT_SERVER_POWERAUTH_SERVICE_SECURITY_CLIENT_SECRET:}

# PowerAuth Push Service configuration
powerauth.push.service.url=${ENROLLMENT_SERVER_PUSH_SERVICE_URL:http://localhost:8080/powerauth-push-server}
powerauth.push.service.restClientConfig.responseTimeout=${ENROLLMENT_SERVER_PUSH_SERVER_RESPONSE_TIMEOUT:60s}
powerauth.push.service.restClientConfig.maxIdleTime=${ENROLLMENT_SERVER_PUSH_SERVER_MAX_IDLE_TIME:200s}

# Enrollment Server Configuration
enrollment-server.mtoken.enabled=${ENROLLMENT_SERVER_MTOKEN_ENABLED:true}
enrollment-server.inbox.enabled=${ENROLLMENT_SERVER_INBOX_ENABLED:true}
enrollment-server.activation-spawn.enabled=${ENROLLMENT_SERVER_ACTIVATION_SPAWN_ENABLED:false}
enrollment-server.admin.enabled=${ENROLLMENT_SERVER_ADMIN_ENABLED:false}
enrollment-server.auth-type=NONE
enrollment-server.flag.reporting=true

# Basic HTTP Settings
spring.security.user.name=
spring.security.user.password=

# OIDC Settings
spring.security.oauth2.resource-server.jwt.issuer-uri=
spring.security.oauth2.resource-server.jwt.audiences=

# User-info configuration
enrollment-server.user-info.provider=${ENROLLMENT_SERVER_USER_INFO_PROVIDER:}
enrollment-server.user-info.rest-provider.allowed-stages=${ENROLLMENT_SERVER_USER_INFO_REST_ALLOWED_STAGES:USER_INFO_ENDPOINT}
enrollment-server.user-info.rest-provider.restClientConfig.baseUrl=${ENROLLMENT_SERVER_USER_INFO_REST_URL:http://localhost:8080/user-info}
enrollment-server.user-info.rest-provider.restClientConfig.httpBasicAuthEnabled=${ENROLLMENT_SERVER_USER_INFO_REST_BASIC_ENABLED:false}
enrollment-server.user-info.rest-provider.restClientConfig.httpBasicAuthUsername=${ENROLLMENT_SERVER_USER_INFO_REST_BASIC_USERNAME:}
enrollment-server.user-info.rest-provider.restClientConfig.httpBasicAuthPassword=${ENROLLMENT_SERVER_USER_INFO_REST_BASIC_PASSWORD:}

# Incoming request debug logging
#logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Configure Correlation HTTP Header
powerauth.service.correlation-header.enabled=${ENROLLMENT_SERVER_CORRELATION_HEADER_ENABLED:false}
powerauth.service.correlation-header.name=${ENROLLMENT_SERVER_CORRELATION_HEADER_NAME:X-Correlation-ID}
powerauth.service.correlation-header.value.validation-regexp=${ENROLLMENT_SERVER_CORRELATION_HEADER_VALUE_VALIDATION_REGEXP:[a-zA-Z0-9\\-]{8,1024}}
# For logging correlation HTTP headers enable the pattern and update correlation header name in the pattern
#logging.pattern.console=%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) [%X{X-Correlation-ID}] %clr(%5p) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}

# Monitoring
management.tracing.sampling.probability=1.0
#management.endpoint.metrics.enabled=true
management.endpoints.web.exposure.include=health,info
management.info.git.mode=simple
#management.endpoint.prometheus.enabled=true
#management.prometheus.metrics.export.enabled=true

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration,\
  org.springframework.boot.actuate.autoconfigure.metrics.jersey.JerseyServerMetricsAutoConfiguration


# Custom Logging Configuration
logging.config=${ENROLLMENT_SERVER_LOGGING:}

# Database Configuration - JNDI
spring.datasource.jndi-name=${ENROLLMENT_SERVER_DATASOURCE_JNDI_NAME:false}

# Database Configuration - Connection pool
spring.datasource.hikari.maximumPoolSize=${ENROLLMENT_SERVER_DATASOURCE_HIKARI_MAX_CONNECTIONS:10}

# Database Configuration - Minimum idle connections
spring.datasource.hikari.minimumIdle=${ENROLLMENT_SERVER_DATASOURCE_HIKARI_MIN_IDLE:10}
