name: Test with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'releases/**'
  pull_request:
    branches:
      - 'develop'
      - 'master'
      - 'releases/**'

jobs:
  maven-tests:
    uses: wultra/wultra-infrastructure/.github/workflows/maven-test.yml@issues/checkout-action-v4
    secrets: inherit